name: pixels2flutter
description: Convert a screenshot to a working Flutter app.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: 3.3.3
  flutter: 3.19.5

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  dotted_border: 2.1.0
  equatable: 2.0.5
  file_picker: 8.0.3
  flutter_animate: 4.5.0
  flutter_bloc: 8.1.5
  flutter_secure_storage: 9.0.0
  flutter_svg: 2.0.10+1
  freezed_annotation: 2.4.1
  get_it: 7.7.0
  github: 9.24.0
  go_router: 13.2.3
  injectable: 2.4.1
  langchain: 0.5.0
  langchain_openai: 0.5.0
  flutter_markdown: 0.6.22+1
  result_dart: 1.1.1
  super_drag_and_drop: 0.8.11
  syntax_highlight: 0.4.0
  url_launcher: 6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.9
  flutter_gen_runner: 5.4.0
  freezed: 2.5.1
  injectable_generator: 2.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_gen:
  output: lib/app/assets
  integrations:
    flutter_svg: true
  assets:
    enabled: true
  fonts:
    enabled: false
  colors:
    enabled: false
