name: pixels2flutter
description: Convert a screenshot to a working Flutter app.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: 3.2.3
  flutter: 3.16.4

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  dotted_border: 2.1.0
  equatable: 2.0.5
  file_picker: 6.1.1
  flutter_animate: 4.3.0
  flutter_bloc: 8.1.3
  flutter_secure_storage: 9.0.0
  flutter_svg: 2.0.9
  freezed_annotation: 2.4.1
  get_it: 7.6.4
  github: 9.20.0
  go_router: 12.1.3
  injectable: 2.3.2
  langchain: 0.3.0
  langchain_openai: 0.3.0
  flutter_markdown: 0.6.18+2
  result_dart: #1.1.0
    git:
      url: https://github.com/davidmigloz/result_dart.git
      ref: 302262ddbba670bbe389e1072000b45bd21cfea3
  super_drag_and_drop: 0.7.3
  syntax_highlight: 0.3.0
  url_launcher: 6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.7
  flutter_gen_runner: 5.3.2
  freezed: 2.4.6
  injectable_generator: 2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_gen:
  output: lib/app/assets
  integrations:
    flutter_svg: true
  assets:
    enabled: true
  fonts:
    enabled: false
  colors:
    enabled: false
